import React from "react";

export const recentList = [
  {
    id: 1,
    avatar: "https://via.placeholder.com/150x150",
    title: 'Need a quick support on setting',
    description: [<span className="jr-link">Joy Parish</span>, "  created ticket 15 mins ago"],
    status: 2
  }, {
    id: 2,
    avatar: "https://via.placeholder.com/150x150",
    title: 'Pre-sale query about the product',
    description: [<span className="jr-link">You</span>, " replied 2 days ago"],
    status: 1
  }, {
    id: 3,
    avatar: "https://via.placeholder.com/150x150",
    title: 'Regarding customization service',
    description: [<span className="jr-link">Joy Parish</span>, " replied 2 days ago"],
    status: 4
  }
];

export const allProperties = [
  {
    id: 1,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 2,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  }
];
export const newJercy = [
  {
    id: 1,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 3,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  },
  {
    id: 2,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },

];
export const colorado = [
  {
    id: 1,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 2,
    image:"https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  }
];
export const albama = [
  {
    id: 1,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  },
  {
    id: 2,
    image:"https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: "https://via.placeholder.com/570x480",
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
];

export const salesStatisticData = [
  {name: 'Jan', uv: 9000},
  {name: 'Feb', uv: 12000},
  {name: 'Mar', uv: 7000},
  {name: 'Apr', uv: 12000},
  {name: 'May', uv: 14000},
  {name: 'Jun', uv: 18500},
  {name: 'Jul', uv: 14000},
  {name: 'Aug', uv: 17000},
  {name: 'Sep', uv: 15000},
  {name: 'Oct', uv: 18000},
  {name: 'Nov', uv: 19500},
  {name: 'Dec', uv: 16000},
];
